-- Migration 009 — Gold lifecycle layer
-- Part of: TravelLens B-040 — per-booking lifecycle reconstruction
-- File:    db/migrations/009_gold_lifecycle.sql
--
-- What this creates / alters:
--
--   1. ingest_seq BIGINT GENERATED BY DEFAULT AS IDENTITY on fact_booking_events
--      Monotonic cursor that the gold updater pages through. Existing rows are
--      backfilled sequentially (ordered by ingested_at, event_id). New inserts
--      auto-fill from the sequence.
--
--   2. fact_booking_lifecycle — GOLD one-row-per-booking table.
--      Forward-only status machine (BOOKED → CHECKED_IN → COMPLETED / CANCELLED).
--      Populated by scripts/gold_lifecycle_updater.py running as a ~1-min
--      micro-batch alongside the consumer (never in the consumer — decoupled so
--      gold latency never back-pressures the silver accept path).
--
--   3. gold_watermark — single-row table tracking the last ingest_seq the gold
--      updater committed. Allows the updater to resume after a restart without
--      reprocessing old events.
--
-- Notes:
--   - PRICE_CHANGE events have no booking_id and are EXCLUDED from gold by the
--     updater query (event_type NOT IN ('PRICE_CHANGE','REVIEW') AND booking_id
--     IS NOT NULL). The gold table never sees them.
--   - REVIEW is a hotel-level event (reviews_raw), not a per-booking lifecycle
--     step. It is also excluded from gold.
--   - illegal_transition_flag fires when an event arrives out of lifecycle order
--     (e.g. CHECKOUT before CHECKIN). The updater keeps the most-advanced status
--     (never regresses) and records the anomaly here.
--   - source_mix ('history'|'stream'|'mixed') tracks whether the lifecycle row
--     was assembled from history-only, stream-only, or both sources. 'mixed'
--     is the expected value for open-backlog bookings (history BOOKING/CHECKIN +
--     stream CHECKOUT after the sim-clock advances past their checkout date).
--
-- Run with:
--   docker exec -i travellens-postgres psql -U travellens -d travellens \
--     < db/migrations/009_gold_lifecycle.sql
--
-- Idempotent — safe to re-run (IF NOT EXISTS / IF NOT EXISTS guards).
-- The backfill UPDATE uses WHERE ingest_seq IS NULL so it is also a no-op on
-- a second run.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add ingest_seq identity column to fact_booking_events
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE fact_booking_events
    ADD COLUMN IF NOT EXISTS ingest_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Backfill existing rows in ingested_at, event_id order so the sequence
-- preserves approximate insertion order. ingested_at is the same for rows
-- written in the same bulk INSERT, so event_id (UUID) breaks ties consistently.
UPDATE fact_booking_events fbe
SET    ingest_seq = sub.rn
FROM (
    SELECT event_id,
           ROW_NUMBER() OVER (ORDER BY ingested_at, event_id) AS rn
    FROM   fact_booking_events
    WHERE  ingest_seq IS NULL
) sub
WHERE fbe.event_id = sub.event_id;

-- Advance the identity sequence past the max assigned value so new inserts
-- never collide with the backfill values.
SELECT setval(
    pg_get_serial_sequence('fact_booking_events', 'ingest_seq'),
    COALESCE((SELECT MAX(ingest_seq) FROM fact_booking_events), 0)
);

CREATE INDEX IF NOT EXISTS idx_fact_booking_events_ingest_seq
    ON fact_booking_events (ingest_seq);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Gold lifecycle table — one row per booking_id
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS fact_booking_lifecycle (
    booking_id              UUID            PRIMARY KEY,

    -- Dimension references (filled by the BOOKING event)
    customer_id             VARCHAR(20),
    hotel_id                VARCHAR(20),
    room_type_id            UUID,
    city                    VARCHAR(50),

    -- Lifecycle timestamps (event_ts of each stage event)
    -- + their sim-day equivalents (event_date of the same event).
    -- booking_ts / booking_date  : when the BOOKING event fired
    -- checkin_ts  / checkin_date : when the CHECKIN  event fired
    -- checkout_ts / checkout_date: when the CHECKOUT event fired
    -- cancellation_ts / date     : when the CANCELLATION event fired
    booking_ts              TIMESTAMPTZ,
    booking_date            DATE,
    checkin_ts              TIMESTAMPTZ,
    checkin_date            DATE,
    checkout_ts             TIMESTAMPTZ,
    checkout_date           DATE,
    cancellation_ts         TIMESTAMPTZ,
    cancellation_date       DATE,

    -- Booking facts from the BOOKING event payload
    nights                  SMALLINT,
    num_guests              SMALLINT,
    nightly_rate_inr        NUMERIC(10,2),
    revenue_inr             NUMERIC(10,2),
    booking_source          VARCHAR(50),
    payment_mode            VARCHAR(20),
    cancellation_reason     VARCHAR(40),

    -- Forward-only lifecycle state machine
    current_status          VARCHAR(20)     NOT NULL DEFAULT 'BOOKED',
    -- outcome: in_progress | completed | cancelled | no_show
    outcome                 VARCHAR(15),

    -- Quality flag: TRUE when an event arrived out of lifecycle order
    -- (status was not regressed, but the anomaly is recorded here).
    illegal_transition_flag BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Provenance: which source(s) contributed events to this row.
    -- history = all events from source='history' (backfill generator)
    -- stream  = all events from source='stream'  (live calendar replay)
    -- mixed   = events from both (expected for open-backlog bookings
    --           whose BOOKING/CHECKIN landed in history but CHECKOUT
    --           arrived from the stream after sim-clock advancement).
    source_mix              VARCHAR(10),

    -- Lifecycle metrics
    event_count             INT             NOT NULL DEFAULT 0,
    first_event_ts          TIMESTAMPTZ,
    last_event_ts           TIMESTAMPTZ,
    last_updated            TIMESTAMPTZ     NOT NULL DEFAULT now(),

    CONSTRAINT fact_booking_lifecycle_status_chk
        CHECK (current_status IN ('BOOKED','CHECKED_IN','COMPLETED','CANCELLED')),
    CONSTRAINT fact_booking_lifecycle_outcome_chk
        CHECK (outcome IS NULL OR outcome IN ('in_progress','completed','cancelled','no_show')),
    CONSTRAINT fact_booking_lifecycle_source_mix_chk
        CHECK (source_mix IS NULL OR source_mix IN ('history','stream','mixed'))
);

CREATE INDEX IF NOT EXISTS idx_fact_booking_lifecycle_hotel_id
    ON fact_booking_lifecycle (hotel_id);
CREATE INDEX IF NOT EXISTS idx_fact_booking_lifecycle_status
    ON fact_booking_lifecycle (current_status);
CREATE INDEX IF NOT EXISTS idx_fact_booking_lifecycle_outcome
    ON fact_booking_lifecycle (outcome);
CREATE INDEX IF NOT EXISTS idx_fact_booking_lifecycle_source_mix
    ON fact_booking_lifecycle (source_mix);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Gold watermark — single-row cursor for the updater
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gold_watermark (
    id              INT         PRIMARY KEY DEFAULT 1,
    last_ingest_seq BIGINT      NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gold_watermark_single_row CHECK (id = 1)
);

-- Seed the watermark row (idempotent — DO NOTHING on conflict).
INSERT INTO gold_watermark (id, last_ingest_seq, updated_at)
VALUES (1, 0, now())
ON CONFLICT (id) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- Verify
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 'migration 009 applied'                                  AS status,
       (SELECT COUNT(*) FROM fact_booking_events
         WHERE ingest_seq IS NULL)                              AS ingest_seq_nulls,
       (SELECT MAX(ingest_seq) FROM fact_booking_events)        AS max_ingest_seq,
       (SELECT COUNT(*) FROM fact_booking_lifecycle)            AS lifecycle_rows,
       (SELECT last_ingest_seq FROM gold_watermark WHERE id=1)  AS watermark;
